version: '3'
services:
    v12:
        image: djs-v12
        build:
          context: ./v12
          dockerfile: Dockerfile
        restart: unless-stopped
        env_file:
          - ./v12/.env
    master:
        image: djs-master
        build:
          context: ./master
          dockerfile: Dockerfile
        restart: unless-stopped
        env_file:
          - ./master/.env
    dev:
        image: dev
        build:
          context: ./dev
          dockerfile: Dockerfile
        restart: unless-stopped
        env_file:
          - ./dev/.env
