name: Lint
on: [push, pull_request]
jobs:
  eslint:
    name: ESLint
    runs-on: macos-latest
    strategy:
      fail-fast: true
      matrix:
        path: [v12, master, dev]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies - ${{matrix.path}}
        working-directory: ./${{matrix.path}}
        run: npm install

      - name: Run ESLint - ${{matrix.path}}
        working-directory: ./${{matrix.path}}
        run: npm run lint
